[package]
name = "gen-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
rand = { version = "0.9.0", features = ["alloc", "thread_rng"] }
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
